[package]
name = "ffxiv_client_structs_generated"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
ffxiv_client_structs_macros = { path = "../macros" }
ffxiv_client_structs_util = { path = "../util" }
tokio = { version = "1", features = ["rt"], optional = true }

[features]
async-resolution = ["tokio"]
